- id: '1699476318512'
  alias: FVICENTE - TV
  description: Turn ON/OFF monitor with Chromecast
  trigger:
  - alias: Chromecast ON
    platform: state
    entity_id:
    - remote.fvicente_tv
    from: 'off'
    to: 'on'
    id: Turn ON Chromecast
  - alias: Chromecast OFF
    platform: state
    entity_id:
    - remote.fvicente_tv
    from: 'on'
    to: 'off'
    id: Turn OFF Chromecast
  condition: []
  action:
  - alias: Chromecast ON / OFF
    choose:
    - conditions:
      - condition: trigger
        id:
        - Turn ON Chromecast
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.fvicente_monitor_switch
      - service: media_player.volume_set
        metadata: {}
        data:
          volume_level: 0.75
        target:
          device_id: fb289c0c16ea235873fa897462835efa
      alias: 'ON'
    - conditions:
      - condition: trigger
        id:
        - Turn OFF Chromecast
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.fvicente_monitor_switch
      - service: media_player.volume_set
        metadata: {}
        data:
          volume_level: 0.25
        target:
          device_id: fb289c0c16ea235873fa897462835efa
      alias: 'OFF'
  mode: single
- id: '1699591191220'
  alias: Phone Chargig
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.fvicente_phone_battery_level
    alias: Battery Changes
  condition: []
  action:
  - alias: CHARGE > 90 / CHARGE < 10
    choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fvicente_phone_battery_level
        above: 90
      sequence:
      - alias: 'CHARGING '
        choose:
        - conditions:
          - condition: state
            entity_id: sensor.fvicente_phone_battery_state
            state: Charging
          sequence:
          - alias: DAY / NIGHT
            choose:
            - conditions:
              - condition: sun
                before: sunset
                after: sunrise
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teléfono ya está cargado, sería buena idea desconectarlo
                  - service: notify.mobile_app_fvicente_phone
                    data:
                      data:
                        push:
                          sound:
                            name: findmy.wav
                            critical: 1
                            volume: 1
                      title: BATERÍA
                      message: Carga completada
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: not_home
                  sequence:
                  - service: notify.mobile_app_fvicente_phone
                    data:
                      message: Tu teléfono ya está cargado, sería buena idea desconectarlo
                  alias: AWAY
              alias: DAY
            - conditions:
              - condition: sun
                before: sunrise
                after: sunset
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teleéfono está cargado, sería buena idea desconectarlo
                  - service: notify.mobile_app_fvicente_phone
                    data:
                      message: Carga completa
                      title: BATERÍA
                      data:
                        push:
                          sound:
                            name: findmy.wav
                            critical: 1
                            volume: 1
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: not_home
                  sequence: []
                  alias: AWAY
              alias: NIGHT
          alias: CHARGING
      alias: BATERY > 90
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fvicente_phone_battery_level
        below: 10
      sequence:
      - alias: CHARGING / NO CHARGING
        choose:
        - conditions:
          - condition: state
            entity_id: sensor.fvicente_phone_battery_state
            state: Not Charging
          sequence:
          - alias: DAY / NIGHT
            choose:
            - conditions:
              - condition: sun
                before: sunset
                after: sunrise
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teléfono se está quedando sin batería , seria bueno
                        ponerlo a cargar
                  - service: notify.mobile_app_fvicente_phone
                    data:
                      message: Tu teléfono se está quedando sin batería , seria bueno
                        ponerlo a cargar
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: not_home
                  sequence:
                  - service: notify.mobile_app_fvicente_phone
                    data:
                      message: Tu teléfono se está quedando sin batería , seria bueno
                        ponerlo a cargar
                  alias: AWAY
              alias: DAY
            - conditions:
              - condition: sun
                before: sunrise
                after: sunset
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teléfono se está descargando, sería buena idea ponerlo
                        a cargar
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_phone
                    state: not_home
                  sequence: []
                  alias: AWAY
              alias: NIGHT
          alias: NO CHARGING
      alias: BATERY < 10
  mode: single
- id: '1704934376320'
  alias: FVICENTE - leave
  description: ''
  trigger:
  - platform: zone
    entity_id: person.fvicente
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.fvicente_backlight_switch
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.fvicente
  - service: remote.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: remote.fvicente_tv
  - service: fan.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: fan.fvicente_fan
  - service: media_player.media_stop
    metadata: {}
    data: {}
    target:
      entity_id: media_player.echo_recamara
  mode: single
- id: '1704934606210'
  alias: FVICENTE - arrive
  description: ''
  trigger:
  - platform: zone
    entity_id: person.fvicente
    zone: zone.home
    event: leave
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.fvicente
  mode: single
- id: '1706750034690'
  alias: HomeAssistant - Start
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: sun
    before: sunset
    after: sunrise
    alias: Solo de dia
  action:
  - service: script.homeassistant_start
    metadata: {}
    data: {}
  mode: single
- id: '1707077020260'
  alias: Reminders - Happy Birthday
  description: ''
  trigger:
  - platform: calendar
    event: start
    offset: 0:0:0
    entity_id: calendar.birthdays
  condition: []
  action:
  - service: notify.alexa_media_echo_recamara
    metadata: {}
    data:
      title: Feliz Cumpleaños!
      message: Felicidades
  mode: single
- id: '1707273663688'
  alias: FVICENTE - wakeup
  description: ''
  use_blueprint:
    path: homeassistant/lights-wakeup.yaml
    input:
      manual_time: 00:00:00
      light_entity: light.fvicente
      check_entity: person.fvicente
      sunrise_duration: 15
      timestamp_sensor: sensor.next_alarm_echo_recamara
      presence_sensor: binary_sensor.fvicente_inhome
      effect_duration: 10
      start_brightness: 5
      min_mired: 20
      post_sunrise_actions:
      - service: media_player.volume_set
        metadata: {}
        data:
          volume_level: 0.3
        target:
          entity_id: media_player.echo_recamara
      - service: media_player.play_media
        metadata: {}
        data:
          media_content_id: album goguear
          media_content_type: SPOTIFY
        target:
          entity_id: media_player.echo_recamara
      - service: fan.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: fan.fvicente_fan
- id: '1707698876630'
  alias: FVICENTE - movie time
  description: ''
  use_blueprint:
    path: homeassistant/lights-movietime.yaml
    input:
      trigger_entities:
      - media_player.fvicente_tv
      trigger_on_state:
      - playing
      app_attribute:
      - Prime Video
      trigger_off_state:
      - 'off'
      off_light_switch:
        entity_id:
        - light.fvicente_backlight_switch
        - light.fvicente
      include_intermission: intermission_enable
      intermission_light_switch:
        entity_id: light.fvicente
      include_sun: sun_enabled
      light_switch:
        entity_id: binary_sensor.fvicente_movietime
      include_start_turn_off: enable_start_turn_off
      include_light_control: []
      light_brightness: 10
      light_colour_temperature: 2500
      light_transition_on: 1.5
      light_transition_off: 1.5
      off_light_transition_off: 1
      intermission_include_light_control:
      - use_brightness
      - use_transition
      - use_colour_temperature
      intermission_light_brightness: 10
      intermission_light_colour_temperature: 2500
      intermission_light_transition_on: 2
      intermission_light_transition_off: 2
      time_delay: 3
- id: '1707986820338'
  alias: HomeAsistant - Restart
  description: ''
  trigger:
  - platform: time
    at: 04:30:00
  condition: []
  action:
  - service: homeassistant.restart
    metadata: {}
    data: {}
  mode: single
- id: '1708389440992'
  alias: NOTIFICATIONS - Garbage
  description: ''
  use_blueprint:
    path: homeassistant/calendar-notifications.yaml
    input:
      calendar: calendar.garbage
      include_calendar_trigger: disable_key_word
      include_start_notify: enable_start_notify_options
      start_notify_device:
      - 3bfd4bb2ffe977888371f72bfe976eec
      include_start_action_button_confirmation: disable_start_action_button_confirmation
      include_end_notify: enable_end_notify_options
      end_notify_device:
      - 3bfd4bb2ffe977888371f72bfe976eec
