- id: '1699476318512'
  alias: GoogleTV - Monitor
  description: Turn ON/OFF monitor with Chromecast
  trigger:
  - alias: Chromecast ON
    platform: state
    entity_id:
    - remote.fvicente_tv
    from: 'off'
    to: 'on'
    id: Turn ON Chromecast
  - alias: Chromecast OFF
    platform: state
    entity_id:
    - remote.fvicente_tv
    from: 'on'
    to: 'off'
    id: Turn OFF Chromecast
  condition: []
  action:
  - alias: Chromecast ON / OFF
    choose:
    - conditions:
      - condition: trigger
        id:
        - Turn ON Chromecast
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.fvicente_monitor_switch
      - service: media_player.volume_set
        metadata: {}
        data:
          volume_level: 0.75
        target:
          device_id: fb289c0c16ea235873fa897462835efa
      alias: 'ON'
    - conditions:
      - condition: trigger
        id:
        - Turn OFF Chromecast
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.fvicente_monitor_switch
      - service: media_player.volume_set
        metadata: {}
        data:
          volume_level: 0.25
        target:
          device_id: fb289c0c16ea235873fa897462835efa
      alias: 'OFF'
  mode: single
- id: '1699591191220'
  alias: Phone Chargig
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.fvicente_iphone_battery_level
    alias: Battery Changes
  condition: []
  action:
  - alias: CHARGE > 90 / CHARGE < 10
    choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fvicente_iphone_battery_level
        above: 90
      sequence:
      - alias: 'CHARGING '
        choose:
        - conditions:
          - condition: state
            entity_id: sensor.fvicente_iphone_battery_state
            state: Charging
          sequence:
          - alias: DAY / NIGHT
            choose:
            - conditions:
              - condition: sun
                before: sunset
                after: sunrise
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teléfono ya está cargado, sería buena idea desconectarlo
                  - service: notify.mobile_app_fvicente_iphone
                    data:
                      data:
                        push:
                          sound:
                            name: findmy.wav
                            critical: 1
                            volume: 1
                      title: BATERÍA
                      message: Carga completada
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: not_home
                  sequence:
                  - service: notify.mobile_app_fvicente_iphone
                    data:
                      message: Tu teléfono ya está cargado, sería buena idea desconectarlo
                  alias: AWAY
              alias: DAY
            - conditions:
              - condition: sun
                before: sunrise
                after: sunset
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teleéfono está cargado, sería buena idea desconectarlo
                  - service: notify.mobile_app_fvicente_iphone
                    data:
                      message: Carga completa
                      title: BATERÍA
                      data:
                        push:
                          sound:
                            name: findmy.wav
                            critical: 1
                            volume: 1
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: not_home
                  sequence: []
                  alias: AWAY
              alias: NIGHT
          alias: CHARGING
      alias: BATERY > 90
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fvicente_iphone_battery_level
        below: 10
      sequence:
      - alias: CHARGING / NO CHARGING
        choose:
        - conditions:
          - condition: state
            entity_id: sensor.fvicente_iphone_battery_state
            state: Not Charging
          sequence:
          - alias: DAY / NIGHT
            choose:
            - conditions:
              - condition: sun
                before: sunset
                after: sunrise
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teléfono se está quedando sin batería , seria bueno
                        ponerlo a cargar
                  - service: notify.mobile_app_fvicente_iphone
                    data:
                      message: Tu teléfono se está quedando sin batería , seria bueno
                        ponerlo a cargar
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: not_home
                  sequence:
                  - service: notify.mobile_app_fvicente_iphone
                    data:
                      message: Tu teléfono se está quedando sin batería , seria bueno
                        ponerlo a cargar
                  alias: AWAY
              alias: DAY
            - conditions:
              - condition: sun
                before: sunrise
                after: sunset
              sequence:
              - alias: HOME / AWAY
                choose:
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: home
                  sequence:
                  - service: notify.alexa_media_echo_recamara
                    data:
                      message: Tu teléfono se está descargando, sería buena idea ponerlo
                        a cargar
                  alias: HOME
                - conditions:
                  - condition: state
                    entity_id: device_tracker.fvicente_iphone
                    state: not_home
                  sequence: []
                  alias: AWAY
              alias: NIGHT
          alias: NO CHARGING
      alias: BATERY < 10
  mode: single
- id: '1704934376320'
  alias: fvicente - leave
  description: ''
  trigger:
  - platform: zone
    entity_id: person.fvicente
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.fvicente_backlight_switch
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.fvicente
  - service: remote.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: remote.fvicente_tv
  - service: fan.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: fan.fvicente_fan
  - service: media_player.media_stop
    metadata: {}
    data: {}
    target:
      entity_id: media_player.echo_recamara
  mode: single
- id: '1704934606210'
  alias: fvicente - arrive
  description: ''
  trigger:
  - platform: zone
    entity_id: person.fvicente
    zone: zone.home
    event: leave
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.fvicente
  mode: single
- id: '1706486611517'
  alias: fvicente_ramdom_Light
  description: ''
  use_blueprint:
    path: homeassistant/night_random_lights.yaml
    input:
      target_light: light.fvicente
      override_switch_entity: input_boolean.automations_off
      away_lighting_switch_entity: input_boolean.automations_away
      lights_out_time: 07:00:00
- id: '1706750034690'
  alias: homeassistant_start
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: script.homeassistant_start
    metadata: {}
    data: {}
  mode: single
- id: '1707009855841'
  alias: Reminders - garbage_collection
  description: Recordatorio de recolección de basura
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: zone
    entity_id: person.fvicente
    zone: zone.home
  - condition: state
    entity_id: calendar.garbage
    state: 'on'
  action:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.4
    target:
      device_id: fb289c0c16ea235873fa897462835efa
  - service: notify.alexa_media_echo_recamara
    metadata: {}
    data:
      message: Recuerda sacar la basura
  mode: single
- id: '1707077020260'
  alias: Reminders - Happy Birthday
  description: ''
  trigger:
  - platform: calendar
    event: start
    offset: 0:0:0
    entity_id: calendar.birthdays
  condition: []
  action:
  - service: notify.alexa_media_echo_recamara
    metadata: {}
    data:
      title: Feliz Cumpleaños!
      message: Felicidades
  mode: single
