fan:
  - platform: template
    fans:
      fvicente_wfan:
        unique_id: fvicente_wfan
        friendly_name: fvicente wfan
        value_template: "{{ states('switch.fvicente_wfan_switch') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.fvicente_wfan_switch    
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.fvicente_wfan_switch
      

homeassistant:
  customize:
    fan.fvicente_wfan:
      icon: mdi:fan