substitutions:
  gpio_RX: GPIO1
  gpio_TX: GPIO3
  
  gpio_PushButton: GPIO0
  gpio_Relay: GPIO12
  gpio_StatusLed: GPIO13
  
esphome:
  platform: esp8266
  board: esp01_1m

#logger:
#  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 5s
    current:
      name: "Current"
      accuracy_decimals: 2
      unit_of_measurement: A
      filters:
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
            send_first_at: 1
        
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      unit_of_measurement: V

    power:
      name: "Load"
      accuracy_decimals: 2
      unit_of_measurement: W

      filters:
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
            send_first_at: 1
