wifi_ssid: "SwitHome"
wifi_password: "CIC070723G78"
ap_password: "Iz022394"

ota_password: "f3e76f462c62c0a7a0bf11c8d4c72324"
api_key: "c4MwmvOhcrUzufarPDQdZwZ8T/GW30/gehbgTEJ1J4c="

mqtt_ip: "192.168.0.250"
mqtt_user: "IoT_Home"
mqtt_password: "Pa$$w0rd"

latitude: "20.541786"
longitude: "-100.404586"