blueprint:
  name: Wake-up light alarm with sunrise effect
  description: 'A wake-up light alarm with a brightness and color temperature sunrise
    effect. Note: Requires date_time_iso sensor in configuration, not manually executable!'
  domain: automation
  input:
    selector:
      device:
      


trigger:
  - platform: sun
    event: sunrise
    offset: 0
condition:
  - condition: not
    conditions:
      - condition: zone
        entity_id: person.fvicente
        zone: zone.home
action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: 8976e33a25d26202fe2025cd680e00f8
mode: single
