homeassistant:
  customize:
    vacuum.aspiradora:
      icon: cil:roborock-vacuum
    sensor.morty_last_clean_end:
      friendly_name: Última limpieza
      icon: mdi:calendar-clock

template:
  - sensor:
      - unique_id: vacuum_filter
        state: >
          {% set entity_id = 'sensor.aspiradora_filter_life' %}
          {{ (states(entity_id) | int(default=0) / 5400) | int(default=0) }}
        attributes:
          friendly_name: Filter
          icon: cil:roborock-filter
          unit_of_measurement: '%'

      - unique_id: vacuum_mainbrush
        state: >
          {% set entity_id = 'sensor.aspiradora_rolling_brush_lifet' %}
          {{ (states(entity_id) | int(default=0) / 10800) | int(default=0) }}
        attributes:
          friendly_name: Cepillo
          icon: cil:roborock-mainbrush
          unit_of_measurement: '%'

      - unique_id: vacuum_sensors
        state: >
          {% set entity_id = 'sensor.aspiradora_side_brush_life' %}
          {{ (states(entity_id) | int(default=0) / 1080) | int(default=0) }}
        attributes:
          friendly_name: Sensorer
          icon: cil:roborock-sensor
          unit_of_measurement: '%'

      - unique_id: vacuum_sidebrush
        state: >
          {% set entity_id = 'sensor.aspiradora_side_brush_life' %}
          {{ (states(entity_id) | int(default=0) / 7200) | int(default=0) }}
        attributes:
          friendly_name: Cepillos laterales
          icon: cil:roborock-sidebrush
          unit_of_measurement: '%'

