sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperature"
    id: _temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

    on_value_range:
      - above: ${max_temp}
        then:
          switch.turn_off: relay
  
  
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    
  - platform: adc
    id: temp_analog_reading
    pin: A0
    